import * as tf from '@tensorflow/tfjs';
console.log('tf version:', tf.version_core);
const baseUrl = 'http://localhost:5176/goal_vector_model';
const metaResp = await fetch(`${baseUrl}/metadata.json`);
const meta = await metaResp.json();
console.log('metadata.output_post_normalize:', meta.output_post_normalize);
console.log('metadata.input_order:', meta.input_order);
const model = await tf.loadLayersModel(`${baseUrl}/model.json`);
console.log('model inputs:', model.inputs.map(i => `${i.name}: ${i.shape}`));
console.log('model outputs:', model.outputs.map(o => `${o.name}: ${o.shape}`));
const ps = meta.patch_size, ns = meta.n_scales, nl = meta.n_landmarks;
const patch = tf.zeros([1, ps, ps, ps, ns]);
const pos = tf.tensor([[0, 0, 0]]);
const target = tf.oneHot([4], nl);
const out = model.predict([patch, pos, target]);
const data = await out.data();
console.log('raw output:', Array.from(data));
const n = Math.hypot(data[0], data[1], data[2]) || 1;
console.log('normalized:', [data[0]/n, data[1]/n, data[2]/n]);
